language: java
jdk: openjdk13

os:
  - linux
  - osx
  
env :
  matrix :
    - LAB : "lab1"
    - LAB : "lab2"
    - LAB : "lab3"
    - LAB : "lab4"
    - LAB : "lab5"
    - LAB : "lab6"
    
script:
  - cd $LAB && mvn package
